export const MAJOR_KEYWORDS = [
  // Product releases
  'release',
  'released',
  'launch',
  'launched',
  'announce',
  'announced',
  'announcement',
  'introducing',
  'introduces',
  'introducing today',
  'available now',
  'general availability',
  'ga',
  'stable',
  'beta',
  'alpha',
  'preview',
  'preview release',
  'release candidate',
  'rc',

  // Major updates
  'major update',
  'breaking change',
  'breaking changes',
  'migration guide',
  'upgrade guide',
  'deprecation',
  'deprecated',
  'sunset',
  'end of life',
  'eol',

  // Security
  'security',
  'security update',
  'security patch',
  'critical',
  'critical vulnerability',
  'high severity',
  'remote code execution',
  'rce',
  'zero day',
  'zero-day',
  'vulnerability',
  'vulnerabilities',
  'exploit',
  'actively exploited',
  'patch',
  'patched',
  'cve',
  'data breach',
  'security breach',

  // AI
  'gpt',
  'gpt-4',
  'gpt-4.1',
  'gpt-5',
  'chatgpt',
  'claude',
  'gemini',
  'llama',
  'mistral',
  'deepseek',
  'qwen',
  'phi',
  'copilot',
  'ai model',
  'foundation model',
  'multimodal',
  'reasoning model',
  'agent',
  'agentic',
  'embedding',
  'transformer',

  // React ecosystem
  'react',
  'react 19',
  'react native',
  'react native 0.',
  'next.js',
  'next.js 15',
  'vite',
  'remix',
  'astro',
  'tanstack',
  'typescript',
  'typescript 5.',
  'javascript',
  'node.js',
  'bun',
  'deno',

  // Backend & Cloud
  'docker',
  'kubernetes',
  'kubernetes 1.',
  'helm',
  'terraform',
  'aws',
  'azure',
  'google cloud',
  'gcp',
  'serverless',

  // Languages
  'rust',
  'rust 1.',
  'go',
  'go 1.',
  'python',
  'java',
  'swift',
  'kotlin',

  // Database
  'postgres',
  'postgresql',
  'mongodb',
  'redis',
  'mysql',
  'sqlite',

  // Business
  'acquisition',
  'acquire',
  'acquired',
  'merger',
  'merging',
  'ipo',
  'funding',
  'series a',
  'series b',
  'series c',
  'investment',
  'valuation',
  'layoffs',
  'bankruptcy',

  // Open Source
  'open source',
  'oss',
  'github',
  'foundation',

  // Standards
  'specification',
  'rfc',
  'proposal',
  'ecmascript',
  'tc39',
];

export const MINOR_KEYWORDS = [
  // Marketing
  'sponsor',
  'sponsored',
  'advertiser',
  'promotion',
  'promo',
  'promotional',
  'marketing',

  // Community engagement
  'giveaway',
  'contest',
  'sweepstakes',
  'raffle',
  'challenge',
  'win prizes',

  // Jobs
  'job',
  'job listing',
  'jobs',
  'hiring',
  'we are hiring',
  'career',
  'career opportunity',
  'vacancy',
  'join our team',
  'apply now',
  'open position',

  // Events
  'webinar',
  'meetup',
  'conference registration',
  'register now',

  // Misc
  'newsletter',
  'subscribe',
  'follow us',
  'like and share',
  'community spotlight',
];

// Articles matching any of these are treated as promotional/advertising
// (e.g. promo codes, coupon codes) and are blocked from being saved.
export const PROMO_BLOCKLIST = [
  'promo code',
  'coupon',
  'coupon code',
  'coupon codes',
  'discount',
  'discount code',
  'discount codes',
  'voucher',
  'voucher code',
  'voucher codes',
  'gift card',
  'cashback',
  'cash back',
  'promo offer',
  'limited offer',
  'special offer',
  'exclusive offer',
  'exclusive deal',
  'deal code',
  'redeem code',
  'redeem now',
  'claim offer',
  'claim now',
  'free shipping',
  'buy one get one',
  'bogo',
  'sale',
  'clearance',
  'flash sale',
  'black friday',
  'cyber monday',
  'affiliate link',
  'affiliate',
  'referral',
  'referral code',
  'refer a friend',
  'partner offer',
  'partner promotion',
  'sponsored post',
  'sponsored by',
  'in partnership with',
  'paid partnership',
  'this post is sponsored',
  'this article is sponsored',
  'advertisement',
  'advertorial',
  'brand collaboration',
];

// Articles matching any of these are treated as adult/pornographic content
// (nudity, sexual content, etc.) and are blocked from being saved.
export const ADULT_BLOCKLIST = [
  'porn',
  'pornhub',
  'pornography',
  'pornographic',
  'xxx',
  'xxxl',
  '18+',
  'adult',
  'adult content',
  'adult entertainment',
  'adult video',
  'adult film',

  'sex',
  'sexual',
  'sexual content',
  'sexual activity',
  'sexual act',
  'sexual video',

  'sex tape',
  'sex scene',
  'sex video',

  'nude',
  'nudity',
  'naked',
  'topless',

  'erotic',
  'erotica',
  'fetish',

  'onlyfans',
  'fansly',

  'cam girl',
  'camgirls',
  'cam model',
  'webcam sex',
  'live cam',

  'escort',
  'escort service',
  'brothel',
  'strip club',
  'stripper',

  'hookup',
  'hook up',
  'adult dating',

  'hot girls',
  'hot guys',
  'sexy',
  'bikini model',

  'nsfw',
  'not safe for work',
];
